// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibreriaClasesHotel.Models;

public partial class Reservacion
{
    public int id { get; set; }

    public int? id_cliente { get; set; }

    public int? id_habitacion { get; set; }

    public int? id_empleado { get; set; }

    public DateTime fecha_inicio { get; set; }

    public int dias_estancia { get; set; }

    public decimal? monto { get; set; }

    public virtual Cliente id_clienteNavigation { get; set; }

    public virtual Empleado id_empleadoNavigation { get; set; }

    public virtual Habitacion id_habitacionNavigation { get; set; }
}