// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibreriaClasesHotel.Models;

public partial class Habitacion
{
    public int id { get; set; }

    public string numero_habitacion { get; set; }

    public string tipo_habitacion { get; set; }

    public decimal precio { get; set; }

    public string estado { get; set; }

    public virtual ICollection<Reservacion> Reservacion { get; set; } = new List<Reservacion>();
}