// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LibreriaClasesHotel.Models;

public partial class Hotel_XContext : DbContext
{
    public Hotel_XContext(DbContextOptions<Hotel_XContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Empleado> Empleado { get; set; }

    public virtual DbSet<Habitacion> Habitacion { get; set; }

    public virtual DbSet<Reservacion> Reservacion { get; set; }

    public virtual DbSet<VistaReservaciones> VistaReservaciones { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Cliente__3213E83FBE9572D9");

            entity.Property(e => e.apellido)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.dni)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.telefono)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Empleado>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Empleado__3213E83F798F6724");

            entity.Property(e => e.apellido)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.direccion)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.telefono)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Habitacion>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Habitaci__3213E83FBB4E0D4A");

            entity.Property(e => e.estado)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.numero_habitacion)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.precio).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.tipo_habitacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Reservacion>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Reservac__3213E83F9957022A");

            entity.Property(e => e.fecha_inicio).HasColumnType("date");
            entity.Property(e => e.monto).HasColumnType("money");

            entity.HasOne(d => d.id_clienteNavigation).WithMany(p => p.Reservacion)
                .HasForeignKey(d => d.id_cliente)
                .HasConstraintName("FK__Reservaci__id_cl__3D5E1FD2");

            entity.HasOne(d => d.id_empleadoNavigation).WithMany(p => p.Reservacion)
                .HasForeignKey(d => d.id_empleado)
                .HasConstraintName("FK__Reservaci__id_em__3F466844");

            entity.HasOne(d => d.id_habitacionNavigation).WithMany(p => p.Reservacion)
                .HasForeignKey(d => d.id_habitacion)
                .HasConstraintName("FK__Reservaci__id_ha__3E52440B");
        });

        modelBuilder.Entity<VistaReservaciones>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VistaReservaciones");

            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.DNI)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Precio).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Telefono)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.fecha_inicio).HasColumnType("date");
            entity.Property(e => e.numero_habitacion)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.tipo_habitacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}