// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibreriaClasesHotel.Models;

public partial class VistaReservaciones
{
    public string Apellido { get; set; }

    public string Nombre { get; set; }

    public string DNI { get; set; }

    public string Telefono { get; set; }

    public string numero_habitacion { get; set; }

    public string tipo_habitacion { get; set; }

    public decimal Precio { get; set; }

    public DateTime fecha_inicio { get; set; }

    public int dias_estancia { get; set; }
}